DROP TABLE IF EXISTS user;
CREATE TABLE user (
    user_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(318) CHARACTER SET utf8 NOT NULL UNIQUE KEY,
    password CHAR(40) NOT NULL,
    salt CHAR(4)
);

DROP TABLE IF EXISTS tank;
CREATE TABLE tank (
    user_id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tank_id INT UNSIGNED NOT NULL,
    name VARCHAR(32) CHARACTER SET utf8 NOT NULL,
    color CHAR(6) NOT NULL,
    program TEXT
);

DROP TABLE IF EXISTS sensor;
CREATE TABLE sensor (
    tank_id INT UNSIGNED NOT NULL,
    sensor_num TINYINT UNSIGNED NOT NULL,
    length TINYINT UNSIGNED NOT NULL,
    angle SMALLINT NOT NULL,
    width SMALLINT UNSIGNED NOT NULL,
    turret BOOLEAN NOT NULL
);

/*
DROP TABLE IF EXISTS kill;
CREATE TABLE kill (
    killer_tank_id INT UNSIGNED NOT NULL,
    killed_tank_id INT UNSIGNED NOT NULL,
    round_id INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS round;
CREATE TABLE round (
    round_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    parameters TEXT NOT NULL,
    result TEXT NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
*/

