#! /bin/sh

if [ "$#" -gt 0 ]; then
    tanks="$@"
else
    echo "Usage: $0 tank1 tank2 [...]"
    echo "Writes ./next-round and ./summary.html"
    exit 1
fi

TANKS_GAME=${TANKS_GAME:-forftanks}
NAV_HTML_INC=${NAV_HTML_INC:-./nav.html.inc} export NAV_HTML_INC

# Add wherever this lives to the search path
PATH=$PATH:$(dirname $0)

if [ -f next-round ]; then
    next=$(cat next-round)
else
    next=0
fi
expr $next + 1 > next-round

fn=$(printf "round-%04d.html" $next)
rfn=$(printf "results-%04d.txt" $next)
jfn=$(printf "round-%04d.json" $next)
cfn="current$$.html";

echo -n "Running round $next... "
$TANKS_GAME $tanks >>$jfn 3>$rfn

cat <<EOF >$fn
<!DOCTYPE html>
<html>
  <head>
    <title>Tanks Round $next</title>
    <script type="application/javascript" src="tanks.js"></script>
    <link rel="stylesheet" href="style.css" type="text/css">
    <script type="application/javascript">
      function go() {
        start("battlefield",
// Start JSON data
EOF
cat $jfn >> $fn
cat <<EOF >>$fn
// end JSON data
      );
}
window.onload = go;
    </script>
  </head>
  <body>
    <h1>Tanks Round $next</h1>
    <div id="game_box"><canvas id="battlefield"></canvas></div>
    <p><span id="fps">0</span> fps</p>
EOF
rank.awk $rfn >>$fn
cat $NAV_HTML_INC >>$fn
cat <<EOF >>$fn
  </body>
</html>
EOF

cat <<EOF >$cfn
<!DOCTYPE html>
<html>
  <head>
    <title>Tanks Round $next</title>
    <script type="application/javascript" src="tanks.js"></script>
    <meta http-equiv="Refresh" content="60" />
    <style type="text/css">
        html {
            background: #222;
        }
        #battlefield {
            border: 1px solid green;
        }
    </style>
    <script type="application/javascript">
      function go() {
        start("battlefield",
// Start JSON data
EOF
cat $jfn >> $cfn
cat <<EOF >>$cfn
// end JSON data
      );
}
window.onload = go;
    </script>
  </head>
  <body>
    <div id="game_box"><canvas id="battlefield"></canvas></div>
EOF
cat <<EOF >>$cfn
  </body>
</html>
EOF

mv "current$$.html" "current.html"

summary.awk $tanks > summary.html.$$
mv summary.html.$$ summary.html

./killmatrix.pl results-*.txt > killmatrix$$.js

mv killmatrix$$.js killmatrix.js

echo "done."

